# -*- coding: utf-8 -*-
"""data_merge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIcLJC3lgHZKpoy7AWRVPCJ7g_LuLZtE
"""

import json

files = ["test_processed.json", "train_processed.json", "validation_processed.json"]

combined = []

for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        combined.extend(data)

for i, item in enumerate(combined):
    item["id"] = f"{i:05d}"

with open("data_processed.json", "w", encoding="utf-8") as f:
    json.dump(combined, f, ensure_ascii=False, indent=2)

import json

files = ["test_tagged.json", "train_tagged.json", "validation_tagged.json"]

combined = []

for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        combined.extend(data)

for i, item in enumerate(combined):
    item["id"] = f"{i:05d}"

with open("data_tagged.json", "w", encoding="utf-8") as f:
    json.dump(combined, f, ensure_ascii=False, indent=2)

!pip install stanza -q

import json
import stanza
from tqdm import tqdm

stanza.download("en")
stanza.download("zh")

en_nlp = stanza.Pipeline(
    lang="en",
    processors="tokenize,pos",
    tokenize_pretokenized=True,
    use_gpu=True
)

zh_nlp = stanza.Pipeline(
    lang="zh",
    processors="tokenize,pos",
    tokenize_pretokenized=True,
    use_gpu=True
)


def stanza_tag_tokens(tokens, language_labels):
    pos_tags = []

    for token, lang in zip(tokens, language_labels):
        if lang == "EN":
            doc = en_nlp([[token]])
        else:
            doc = zh_nlp([[token]])

        try:
            upos = doc.sentences[0].words[0].upos
        except Exception:
            upos = "X"

        pos_tags.append([token, upos])

    return pos_tags


input_file = "data_processed.json"
output_file = "data_stanza_gold.json"

with open(input_file, "r", encoding="utf-8") as f:
    data = json.load(f)

new_data = []

for item in tqdm(data):
    tokens = item["tokens"]
    language_labels = item.get("language_labels", item.get("labels"))

    stanza_pos_tags = stanza_tag_tokens(tokens, language_labels)

    new_item = item.copy()
    new_item["gold_pos_tags"] = stanza_pos_tags

    new_data.append(new_item)

with open(output_file, "w", encoding="utf-8") as f:
    json.dump(new_data, f, ensure_ascii=False, indent=2)

print("Saved to:", output_file)

